name: postgres

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=
    networks:
     - ai-assistant-network
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  postgres:
    external: true
    name: postgres

networks:
  ai-assistant-network:
    external: true
    name: ai-assistant-network
