version: '3.7'

services:
  langfuse:
    image: ghcr.io/langfuse/langfuse:latest
    networks:
     - app
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:Mfcd62!!Mfcd62!!@postgres:5432/langfuse
      - NEXTAUTH_SECRET=acf1e6b822dc3354fad25c2f147aed735b67b777488e1a1233c9eda0b3a5b695
      - SALT=b148eb5c59f246a6a111dff71dcb1bcb
      - NEXTAUTH_URL=http://localhost:3006
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - NEXT_PUBLIC_SIGN_UP_DISABLED=${NEXT_PUBLIC_SIGN_UP_DISABLED:-false}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
    # deploy:
    #   mode: replicated
    #   replicas: 1
    #   placement:
    #       constraints:
    #         - node.role == manager
    #   resources:
    #       limits:
    #         cpus: '0.5'
    #         memory: 1024M
    #   labels:
    #     - traefik.enable=true
    #     - traefik.http.routers.langfuse.rule=Host(`localhost:3006`)
    #     - traefik.http.routers.langfuse.entrypoints=websecure
    #     - traefik.http.routers.langfuse.tls.certresolver=letsencryptresolver
    #     - traefik.http.services.langfuse.loadbalancer.server.port=3000
    #     - traefik.http.services.langfuse.loadbalancer.passHostHeader=true
    #     - traefik.http.routers.langfuse.service=langfuse
networks:
  app:
    external: true
    name: bridge